--------------------------------------------------------
--  File created - Wednesday-November-12-2025   
--------------------------------------------------------
DROP TABLE "RAYENSQL"."EMPLOYE" cascade constraints;
DROP TABLE "RAYENSQL"."EVENMENT" cascade constraints;
DROP TABLE "RAYENSQL"."FINANCER" cascade constraints;
DROP TABLE "RAYENSQL"."GERER" cascade constraints;
DROP TABLE "RAYENSQL"."LOGIN" cascade constraints;
DROP TABLE "RAYENSQL"."MATRIEL" cascade constraints;
DROP TABLE "RAYENSQL"."PARTICIPANT" cascade constraints;
DROP TABLE "RAYENSQL"."PARTICIPER" cascade constraints;
DROP TABLE "RAYENSQL"."SPONSOR" cascade constraints;
DROP TABLE "RAYENSQL"."UTILISER" cascade constraints;
DROP TABLE "RAYENSQL"."EMPLOYE" cascade constraints;
DROP TABLE "RAYENSQL"."EVENMENT" cascade constraints;
DROP TABLE "RAYENSQL"."FINANCER" cascade constraints;
DROP TABLE "RAYENSQL"."GERER" cascade constraints;
DROP TABLE "RAYENSQL"."LOGIN" cascade constraints;
DROP TABLE "RAYENSQL"."MATRIEL" cascade constraints;
DROP TABLE "RAYENSQL"."PARTICIPANT" cascade constraints;
DROP TABLE "RAYENSQL"."PARTICIPER" cascade constraints;
DROP TABLE "RAYENSQL"."SPONSOR" cascade constraints;
DROP TABLE "RAYENSQL"."UTILISER" cascade constraints;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."EMPLOYE" 
   (	"ID_EMPLOYE" VARCHAR2(20) NOT NULL ENABLE, 
	"NOM" VARCHAR2(20), 
	"POSTE" VARCHAR2(20), 
	"EMAIL" VARCHAR2(20), 
	"STATUT_DEM" VARCHAR2(20), 
	 CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table EVENMENT
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."EVENMENT" 
   (	"ID_EVENT" VARCHAR2(20) NOT NULL ENABLE, 
	"NOMEVENT" VARCHAR2(20), 
	"DATEE" VARCHAR2(20), 
	"RESPONSABLE" VARCHAR2(20), 
	"STATUT" VARCHAR2(20), 
	"RAMARQUE" VARCHAR2(20), 
	 CONSTRAINT "EVENMENT_PK" PRIMARY KEY ("ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table FINANCER
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."FINANCER" 
   (	"ID_SPONSOR" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_EVENT" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "FINANCER_PK" PRIMARY KEY ("ID_SPONSOR", "ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table GERER
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."GERER" 
   (	"ID_EVENT" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_EMPLOYE" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "GERER_PK" PRIMARY KEY ("ID_EVENT", "ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."LOGIN" 
   (	"USERNAME" VARCHAR2(20) NOT NULL ENABLE, 
	"PWD" VARCHAR2(20), 
	 CONSTRAINT "LOGIN_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table MATRIEL
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."MATRIEL" 
   (	"ID_MAT" VARCHAR2(20) NOT NULL ENABLE, 
	"NOMMAT" VARCHAR2(20), 
	"QUANTITE" VARCHAR2(20), 
	"DISPONIBILITE" VARCHAR2(20), 
	 CONSTRAINT "MATRIEL_PK" PRIMARY KEY ("ID_MAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table PARTICIPANT
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."PARTICIPANT" 
   (	"ID_PAT" VARCHAR2(20) NOT NULL ENABLE, 
	"NOM" VARCHAR2(20), 
	"PRENOM" VARCHAR2(20), 
	"AGE" VARCHAR2(20), 
	"EMAIL" VARCHAR2(20), 
	"TEL" VARCHAR2(20), 
	"TYPE" VARCHAR2(20), 
	 CONSTRAINT "PARTICIPANT_PK" PRIMARY KEY ("ID_PAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table PARTICIPER
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."PARTICIPER" 
   (	"ID_PAT" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_EVENT" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PARTICIPER_PK" PRIMARY KEY ("ID_PAT", "ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table SPONSOR
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."SPONSOR" 
   (	"ID_SPONSOR" VARCHAR2(20) NOT NULL ENABLE, 
	"NOM" VARCHAR2(20), 
	"NIVEAU" VARCHAR2(20), 
	"POURCENTAGE" VARCHAR2(20), 
	 CONSTRAINT "SPONSOR_PK" PRIMARY KEY ("ID_SPONSOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table UTILISER
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."UTILISER" 
   (	"ID_MAT" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_EVENT" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "UTILISER_PK" PRIMARY KEY ("ID_MAT", "ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."EMPLOYE" 
   (	"ID_EMPLOYE" VARCHAR2(20) NOT NULL ENABLE, 
	"NOM" VARCHAR2(20), 
	"POSTE" VARCHAR2(20), 
	"EMAIL" VARCHAR2(20), 
	"STATUT_DEM" VARCHAR2(20), 
	 CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table EVENMENT
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."EVENMENT" 
   (	"ID_EVENT" VARCHAR2(20) NOT NULL ENABLE, 
	"NOMEVENT" VARCHAR2(20), 
	"DATEE" VARCHAR2(20), 
	"RESPONSABLE" VARCHAR2(20), 
	"STATUT" VARCHAR2(20), 
	"RAMARQUE" VARCHAR2(20), 
	 CONSTRAINT "EVENMENT_PK" PRIMARY KEY ("ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table FINANCER
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."FINANCER" 
   (	"ID_SPONSOR" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_EVENT" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "FINANCER_PK" PRIMARY KEY ("ID_SPONSOR", "ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table GERER
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."GERER" 
   (	"ID_EVENT" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_EMPLOYE" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "GERER_PK" PRIMARY KEY ("ID_EVENT", "ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."LOGIN" 
   (	"USERNAME" VARCHAR2(20) NOT NULL ENABLE, 
	"PWD" VARCHAR2(20), 
	 CONSTRAINT "LOGIN_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table MATRIEL
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."MATRIEL" 
   (	"ID_MAT" VARCHAR2(20) NOT NULL ENABLE, 
	"NOMMAT" VARCHAR2(20), 
	"QUANTITE" VARCHAR2(20), 
	"DISPONIBILITE" VARCHAR2(20), 
	 CONSTRAINT "MATRIEL_PK" PRIMARY KEY ("ID_MAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table PARTICIPANT
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."PARTICIPANT" 
   (	"ID_PAT" VARCHAR2(20) NOT NULL ENABLE, 
	"NOM" VARCHAR2(20), 
	"PRENOM" VARCHAR2(20), 
	"AGE" VARCHAR2(20), 
	"EMAIL" VARCHAR2(20), 
	"TEL" VARCHAR2(20), 
	"TYPE" VARCHAR2(20), 
	 CONSTRAINT "PARTICIPANT_PK" PRIMARY KEY ("ID_PAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table PARTICIPER
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."PARTICIPER" 
   (	"ID_PAT" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_EVENT" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PARTICIPER_PK" PRIMARY KEY ("ID_PAT", "ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table SPONSOR
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."SPONSOR" 
   (	"ID_SPONSOR" VARCHAR2(20) NOT NULL ENABLE, 
	"NOM" VARCHAR2(20), 
	"NIVEAU" VARCHAR2(20), 
	"POURCENTAGE" VARCHAR2(20), 
	 CONSTRAINT "SPONSOR_PK" PRIMARY KEY ("ID_SPONSOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table UTILISER
--------------------------------------------------------

  CREATE TABLE "RAYENSQL"."UTILISER" 
   (	"ID_MAT" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_EVENT" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "UTILISER_PK" PRIMARY KEY ("ID_MAT", "ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
REM INSERTING into RAYENSQL.EMPLOYE
SET DEFINE OFF;
Insert into RAYENSQL.EMPLOYE (ID_EMPLOYE,NOM,POSTE,EMAIL,STATUT_DEM) values ('ah5047','ahmed','tolier','ah@g.j','passe');
REM INSERTING into RAYENSQL.EVENMENT
SET DEFINE OFF;
Insert into RAYENSQL.EVENMENT (ID_EVENT,NOMEVENT,DATEE,RESPONSABLE,STATUT,RAMARQUE) values ('acab','medali','12/10/2020','caca','actif','aa');
Insert into RAYENSQL.EVENMENT (ID_EVENT,NOMEVENT,DATEE,RESPONSABLE,STATUT,RAMARQUE) values ('acaba','medali','12/10/2020','caca','actif','aa');
REM INSERTING into RAYENSQL.FINANCER
SET DEFINE OFF;
REM INSERTING into RAYENSQL.GERER
SET DEFINE OFF;
REM INSERTING into RAYENSQL.LOGIN
SET DEFINE OFF;
Insert into RAYENSQL.LOGIN (USERNAME,PWD) values ('dali','1234');
Insert into RAYENSQL.LOGIN (USERNAME,PWD) values ('haddi','12345');
Insert into RAYENSQL.LOGIN (USERNAME,PWD) values ('ranim','&é"''(');
Insert into RAYENSQL.LOGIN (USERNAME,PWD) values ('monta','2025');
Insert into RAYENSQL.LOGIN (USERNAME,PWD) values ('u','u');
Insert into RAYENSQL.LOGIN (USERNAME,PWD) values ('rayen abidi','esprit');
REM INSERTING into RAYENSQL.MATRIEL
SET DEFINE OFF;
Insert into RAYENSQL.MATRIEL (ID_MAT,NOMMAT,QUANTITE,DISPONIBILITE) values ('chair_8','korsi25','25','oui');
Insert into RAYENSQL.MATRIEL (ID_MAT,NOMMAT,QUANTITE,DISPONIBILITE) values ('aadada','adada','20','oui');
Insert into RAYENSQL.MATRIEL (ID_MAT,NOMMAT,QUANTITE,DISPONIBILITE) values ('100','kilyn','0','oui');
Insert into RAYENSQL.MATRIEL (ID_MAT,NOMMAT,QUANTITE,DISPONIBILITE) values ('afaf','fafa','1','affa');
Insert into RAYENSQL.MATRIEL (ID_MAT,NOMMAT,QUANTITE,DISPONIBILITE) values ('aaaaaaaaaaaaaa','aaaaaaaaaaa','20','oui');
Insert into RAYENSQL.MATRIEL (ID_MAT,NOMMAT,QUANTITE,DISPONIBILITE) values ('baf12365','baffle12','1','oui');
REM INSERTING into RAYENSQL.PARTICIPANT
SET DEFINE OFF;
Insert into RAYENSQL.PARTICIPANT (ID_PAT,NOM,PRENOM,AGE,EMAIL,TEL,TYPE) values ('acacbbafaf','fafafafaf','fafaffaaf','12','c@g.com','5040359','1');
Insert into RAYENSQL.PARTICIPANT (ID_PAT,NOM,PRENOM,AGE,EMAIL,TEL,TYPE) values ('acab1312','mohammed ali','hammemi','20','chiha@g.com','212121','1');
REM INSERTING into RAYENSQL.PARTICIPER
SET DEFINE OFF;
REM INSERTING into RAYENSQL.SPONSOR
SET DEFINE OFF;
Insert into RAYENSQL.SPONSOR (ID_SPONSOR,NOM,NIVEAU,POURCENTAGE) values ('aaaaaaaaaaa1','aa','1','13');
Insert into RAYENSQL.SPONSOR (ID_SPONSOR,NOM,NIVEAU,POURCENTAGE) values ('aaaaaaaaaaa2','aa','1','13');
REM INSERTING into RAYENSQL.UTILISER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAYENSQL"."EMPLOYE_PK" ON "RAYENSQL"."EMPLOYE" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index EVENMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAYENSQL"."EVENMENT_PK" ON "RAYENSQL"."EVENMENT" ("ID_EVENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index FINANCER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAYENSQL"."FINANCER_PK" ON "RAYENSQL"."FINANCER" ("ID_SPONSOR", "ID_EVENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index GERER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAYENSQL"."GERER_PK" ON "RAYENSQL"."GERER" ("ID_EVENT", "ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index LOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAYENSQL"."LOGIN_PK" ON "RAYENSQL"."LOGIN" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index MATRIEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAYENSQL"."MATRIEL_PK" ON "RAYENSQL"."MATRIEL" ("ID_MAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index PARTICIPANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAYENSQL"."PARTICIPANT_PK" ON "RAYENSQL"."PARTICIPANT" ("ID_PAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index PARTICIPER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAYENSQL"."PARTICIPER_PK" ON "RAYENSQL"."PARTICIPER" ("ID_PAT", "ID_EVENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SPONSOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAYENSQL"."SPONSOR_PK" ON "RAYENSQL"."SPONSOR" ("ID_SPONSOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index UTILISER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RAYENSQL"."UTILISER_PK" ON "RAYENSQL"."UTILISER" ("ID_MAT", "ID_EVENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "RAYENSQL"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "RAYENSQL"."EMPLOYE" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EVENMENT
--------------------------------------------------------

  ALTER TABLE "RAYENSQL"."EVENMENT" ADD CONSTRAINT "EVENMENT_PK" PRIMARY KEY ("ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "RAYENSQL"."EVENMENT" MODIFY ("ID_EVENT" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table FINANCER
--------------------------------------------------------

  ALTER TABLE "RAYENSQL"."FINANCER" ADD CONSTRAINT "FINANCER_PK" PRIMARY KEY ("ID_SPONSOR", "ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "RAYENSQL"."FINANCER" MODIFY ("ID_EVENT" NOT NULL ENABLE)
  ALTER TABLE "RAYENSQL"."FINANCER" MODIFY ("ID_SPONSOR" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table GERER
--------------------------------------------------------

  ALTER TABLE "RAYENSQL"."GERER" ADD CONSTRAINT "GERER_PK" PRIMARY KEY ("ID_EVENT", "ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "RAYENSQL"."GERER" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE)
  ALTER TABLE "RAYENSQL"."GERER" MODIFY ("ID_EVENT" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "RAYENSQL"."LOGIN" ADD CONSTRAINT "LOGIN_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "RAYENSQL"."LOGIN" MODIFY ("USERNAME" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table MATRIEL
--------------------------------------------------------

  ALTER TABLE "RAYENSQL"."MATRIEL" ADD CONSTRAINT "MATRIEL_PK" PRIMARY KEY ("ID_MAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "RAYENSQL"."MATRIEL" MODIFY ("ID_MAT" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table PARTICIPANT
--------------------------------------------------------

  ALTER TABLE "RAYENSQL"."PARTICIPANT" ADD CONSTRAINT "PARTICIPANT_PK" PRIMARY KEY ("ID_PAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "RAYENSQL"."PARTICIPANT" MODIFY ("ID_PAT" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table PARTICIPER
--------------------------------------------------------

  ALTER TABLE "RAYENSQL"."PARTICIPER" ADD CONSTRAINT "PARTICIPER_PK" PRIMARY KEY ("ID_PAT", "ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "RAYENSQL"."PARTICIPER" MODIFY ("ID_EVENT" NOT NULL ENABLE)
  ALTER TABLE "RAYENSQL"."PARTICIPER" MODIFY ("ID_PAT" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table SPONSOR
--------------------------------------------------------

  ALTER TABLE "RAYENSQL"."SPONSOR" ADD CONSTRAINT "SPONSOR_PK" PRIMARY KEY ("ID_SPONSOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "RAYENSQL"."SPONSOR" MODIFY ("ID_SPONSOR" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table UTILISER
--------------------------------------------------------

  ALTER TABLE "RAYENSQL"."UTILISER" ADD CONSTRAINT "UTILISER_PK" PRIMARY KEY ("ID_MAT", "ID_EVENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "RAYENSQL"."UTILISER" MODIFY ("ID_EVENT" NOT NULL ENABLE)
  ALTER TABLE "RAYENSQL"."UTILISER" MODIFY ("ID_MAT" NOT NULL ENABLE)
